### ISSUE TITLE
checkout previously known devices after a server reset

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#102]
I end up resetting the datastore a lot during development and I'm noticing some weird behavior around that, especially if there are still devices out there that have a valid enrollment profile. 

The default behavior of an unknown UDID trying to `/connect` should be to return a 401, which would cause the device to un-enroll. 
This is also security 101. 

However, because the results of an unauthorized error are so drastic (immediate removal of the enrollment profile), we should create a custom error like `UnauthroizedDeviceRequest` and test it properly.

**Comment by jessepeterson** [comment]
I would definitely not default to 401 (un-enrolling) devices. I could envision a trivial operation (say, moving the database to another host or something and forgetting a piece) and boom, unenrolling an entire fleet.

**Comment by jessepeterson** [comment]
I suspect we have enough protections in place now that this issue is no longer a problem.  We validate the client certificate against  either the SCEP DB (default) or the SCEP CA cert. In the former case a database reset would just invalidate any connecting client (as no cert would exist for it). Also by default we specifically validate UDID-to-cert associations so a database reset would now allow existing clients to talk to the server (as no association would exist). Closing:  resolved.
