### ISSUE TITLE
help the user with anchor certs if the server certificate is self signed

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#107]
from the MDM reference:

> Optional. Array of strings. Each string should contain a DER-encoded certificate converted to Base64 encoding. If provided, these certificates are used as trusted anchor certificates when evaluating the trust of the connection to the MDM server URL. Otherwise, the built-in root certificates are used.

most users work with PEM certificates, so it would be great to provide some sort of helper for anchor certificates. Maybe the template for the DEP profile can auto-set them?

**Comment by jessepeterson** [comment]
Not only for anchor certs (for DEP) but also as a trusted cert in the enrollment profile. Tangentially related to #95 as the TLS cert could be issue by the MicroMDM CA (and thus already trusted by the enrollment profile as it would be included there).

**Comment by jessepeterson** [comment]
There's a couple different avenues to take on this:

1. In `cmd/mdmctl/apply_dep_profile.go` _template_ generation code we could use the HTTPS cert that mdmctl is connecting to and insert that into the template file. We could do this conditionally depending on if the `skip-verify` configuration parameter is specified, too. E.g. `apply dep-profiles -template -use-server-cert-as-anchor` (or just no additional flag, use the `skip-verify` to do it automatically.
2. We could add a separate switch to the _template_ generation code that points to an arbitrary PEM certificate which gets included in the generated template. E.g. `apply dep-profiles -template -anchor /path/cert.pem`.
3. We could add a switch to the actual profile _apply_ step (that contacts the API endpoint) to tell micromdm to include the server's current HTTPS certificate in the DEP profile on behalf of mdmctl. I.e. `apply dep-profiles -f profile.json -insert-server-anchor` or something. This is nice because mdmctl just need not worry about which cert to use.

Which seems most appealing? I like something that's more on the explicit side so 2 or 3 seem best. It could also be some combination of the above. One consideration in all of the above is handling the server-side of things if micromdm is running without TLS at all (e.g. behind a reverse proxy) then it may not know about which certificates to trust per se, in which case 2 would work best.

Thoughts welcome!

**Comment by jessepeterson** [comment]
Sounds like we're going with a combo of 1 and 2 per Slack conversations.
