### ISSUE TITLE
UX for DEP profiles

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#170]
Right now the interface for interacting with DEP profiles looks like this: 

Define a DEP profile -- a JSON blob with keys/values including device serials.
```
{
  "profile_name": "(Required) Human readable name",
  "url": "https://mymdm.example.org/mdm/enroll",
  "allow_pairing": true,
  "is_supervised": false,
  "is_multi_user": false,
  "is_mandatory": false,
  "await_device_configured": false,
  "is_mdm_removable": true,
  "support_phone_number": "(Optional) +1 408 555 1010",
  "support_email_address": "(Optional) support@example.com",
  "org_magic": "(Optional)",
  "anchor_certs": [],
  "supervising_host_certs": [],
  "skip_setup_items": ["AppleID", "Android"],
  "department": "(Optional) support@example.com",
  "devices": ["SERIAL1","SERIAL2"]
}
```

Defining a profile returns back a UUID. 

Now, a user wants to either 
a) update the profiles options.
b) add more devices to the list. 

The interface is a bit messy, because DEP profiles themselves are immutable (except for the devices field). We use a separate API method, called "assign device" for adding devices, but then the user needs to know what the original UUID of the profile was. 

I suggest we add a few wrappers arround `dep.Profile` inside micromdm, and change the user interface to the following:
```
{
  "uuid" : ""
  "profile_name": "(Required) Human readable name",
  "url": "https://mymdm.example.org/mdm/enroll",
   [...]
   "devices": ["SERIAL1","SERIAL2"]
}
```

Here we add a UUID field and create a well defined MDM profile. When the profile is defined initially, we populate the UUID. Now the user can re-apply the same file. When that happens, we fetch the profile using the stored UUID, and see what's changed. 
- If all the keys are the same, we take the device array and assign them to the same UUID. 
- If the keys have been updated, we define a new profile and update the UUID field.

With this proposed change we would remove the need to expose both the define and assign profile APIs to the end user and hopefully simplify this interaction. 

Thoughts?

**Comment by groob** [comment]
hmmmm.. I just realized that it looks like the DEP service already keeps track of some of this state. 

I had a local profile JSON that I re-applied, and got back the same UUID string!

**Comment by jessepeterson** [comment]
I spent some time with this today. It appears that as long as the DEP profile remains largely (if not completely) the same it will automagically re-use the same DEP profile when re-sending it to Apple. Another way to think about is that the profile has a hash function run over it and somehow the UUID is based on this. In my testing it appears that all fields, for any changes, will generate a new UUID _except_ for these fields:

* `allow_pairing`
* `auto_advance_setup`
* `devices`

This means that, importantly, you can add devices to the same profile without generating a new DEP profile UUID.

This has a potential concern whereby folks might need to keep around their original DEP profile JSON files to modify. However in my (very breif) testing with `mdmctl` it appears you can get the DEP profile from the DEP service, have it marshalled to and unmarhsalled from JSON (dropping some fields completely due to their default false value and `omitempty` status) and it will still retain the same UUID. However, I remain suspicious there may be problems here.

**Comment by groob** [comment]
After working with DEP profiles for a while, this is a non-problem.

**Comment by zxyzhouxiaoyun** [comment]
How does  profiles  work?

**Comment by xastherion** [comment]
That is a little short question for a maybe too long answer. Why here in this thread? I think is a wrong thread. If you don't have some experience, maybe look before in "iMazing Profile Editor" to start, or with "Apple Configurator" ;-)
