### ISSUE TITLE
how to change SCEP certificate info

### ISSUE THREAD

**Issue by davisbra** [micromdm/micromdm#476]
how to change SCEP certificate information from Oraganazation unit:MICROMDM SCEP CA and organazation:MicroMDM
 to my own office information?
is this possible?

**Comment by jessepeterson** [comment]
These details are currently hardcoded into the scep server's storage layer and not customizable. I.e. here:

https://github.com/micromdm/scep/blob/e6079f0f186a5fe24a5c576fccd4b7b19a9cfb73/depot/bolt/depot.go#L263

At the moment you would need to edit that dependency's code and recompile MicroMDM.

**Comment by davisbra** [comment]
I change this line of code in vendor/github/micromdm/scep
but when I run make it not changed,also I run make deps and its download dependecies agan and my changes destroyed.
can you discribe to to change this please?

**Comment by davisbra** [comment]
I also create a fork from scep and change this line there .how can i change micromdm to download scep dependeci from this fork?

**Comment by knightsc** [comment]
@davisbra If you edit the file in the vendor directory it should work. Like you already mentioned you will not want to run `make deps` because that will pull down the original files again. I think the server might generate and store the SCEP cert so you would want to remove the previous one after rebuilding. If you haven't set a specific config directory I believe that file would be in the `/var/db/micromdm` folder. If you did want to use your own fork I believe you would want to edit the `Gopkg.toml` file and change the scep entry to something like the following

```
[[override]]
  name = "github.com/micromdm/scep"
  branch = "<yourbranch>"
  source = "github.com/<yourname>/scep"
```

**Comment by knightsc** [comment]
I am going to close this issue out since I think the original question has been answered. https://github.com/micromdm/micromdm/issues/278 is still out there open as a feature request to make this easier along with https://github.com/micromdm/micromdm/issues/232 requesting the ability to provide your own CA cert.
