### ISSUE TITLE
Proposal: Extend the Commands endpoint to allow the caller to specify a custom UUID for the command

### ISSUE THREAD

**Issue by ezhes** [micromdm/micromdm#671]
Currently, the command UUID is just a UUID and is generated by MicroMDM at call time. This pure UUID approach isn't actually a requirement and instead, as is often done in Apple's documentation, can be paired with arbitrary information to provide context information about the request when the device fulfills the request. While it might get me heckled, an interesting possible use of the UUID field could be as a JWT-like authenticated state value which instructs some custom webhook server on how it should handle the eventual response without needing to maintain a database of all commands and their purposes. 

My proposal therefore is that MicroMDM should allow the `/Command` API consumer to, optionally, specify an arbitrary UUID so that applications built off of MicroMDM can encode whatever data they want. If the consumer does not provide a UUID, the current behavior of generating a UUID should be used. 

As far as I can see, this is pretty much a <5 line change to [Command.go](https://github.com/micromdm/micromdm/blob/39230bbdfe395412d3ea50629418512b42d058bb/mdm/mdm/command.go#L18) and something I could definitely toss in a pull if others think this is a worthwhile idea.

**Comment by jessepeterson** [comment]
I thought we already had an issue somewhere for this actually, but looking now maybe it was just a discussion. There's another reason why you might want to provide the command UUID yourself: to avoid race conditions. I.e. if you need to prepare for an incoming command UUID somehow (say, setting database records) then you have a race between your preparation and the command response actually getting returned because the command API both generates a UUID itself, sends the command, and returns the UUID to you. I'd definitely consider a PR for this.

**Comment by groob** [comment]
Totally onboard with what Jesse said. And I've seen timestamps used by other implementations. Please send a PR!

> JWT-like authenticated state

Just an aside, I've done things like this here and there, and I want to propose an alternative that usually ends up simpler: Create an opaque token and associate it with some other metadata in a database. Then look it up/etc.

**Comment by jessepeterson** [comment]
Implemented in #754.
