### ISSUE TITLE
[Question] How to enable attributes in mobileconfigs? (e.g. {{serial_number}})

### ISSUE THREAD

**Issue by Flow-loic** [micromdm/micromdm#676]
Hi,

I was able to use all of my already existing mobileconfigs I wrote for our current (external) MDM Server, except for one thing in our login screen profile.
This profile hides the power options (shut down, restart, sleep) and enables to change the input layout, this works. But unfortunately instead of showing the Serial number I just see {{serial_number}}.
I have been searching the documentation and the web but couldn't find anything helpful.
Is there a way to enable these attributes and if so how?

Thanks and best Regards
Loïc

**Comment by groob** [comment]
Having something like {{serial_number}} templated in profiles is out of scope for the current version of micromdm. This is not a missing feature, since configuration profiles don't have this property by themselves. It's an add-on that your commercial product built for you. 

The way I imagine it works is that the MDM server maintains a database of common attributes for the device (like serial number) and replaces the relevant values when it compiles your template for the device. MicroMDM on the other hand _always_ sends the exact bits you give it to the device. 

Building a templating feature is possible, and it's up to you to do so. MicroMDM gives you the primitives like webhook so you can build your own automation. Think if MicroMDM as a dependency for an MDM, not as a product you should be using directly to manage your devices. 

- https://github.com/micromdm/micromdm/blob/master/docs/user-guide/introduction.md#not-a-product

- https://github.com/micromdm/micromdm/blob/master/docs/user-guide/api-and-webhooks.md

**Comment by Flow-loic** [comment]
Hi Victor,

Ah I see, thanks for clarifying! I wasn't aware this isn't a native MDM function and your explanation on how it must work makes sense. Since this is pretty much the only thing missing we'll probably just leave it.
Thanks for your support and of course for microMDM in general!

Best regards
Loïc
