### ISSUE TITLE
Migrator was missing after refactoring main.go

### ISSUE THREAD

**Issue by zhangchn** [micromdm/micromdm#69]
In commit 2751a79, main.go got refactored for #49.

However, some code deleted was not added back to other sources. In particular, the migrator calls have been missing since the this commit. Without these calls, the pg migration SQLs would not be executed, leading to an empty DB after fresh installs, which in return renders the server unusable.

**Comment by groob** [comment]
Good catch. The reason they were removed is because I'd like the migrations to be external (via a subcommand) 

Would you like to submit a PR that adds the migrations? I scaffolded a `cli` package here:
https://github.com/micromdm/micromdm/blob/3caac17a662385b2df5b5a8743829efbf815479f/cli/main.go

Something like `micromdm run_migrations` would be great.

**Comment by groob** [comment]
We made some significant changes to the code, and the current version of micromdm does not require Postgres. Closing this issue, but keep an eye out for an updated readme over the next few days.
