### ISSUE TITLE
Tools API commands not executing correctly

### ISSUE THREAD

**Issue by NithinMD** [micromdm/micromdm#765]
### What version of `micromdm` are you using?
1.7.1

### What `micromdm` command did you run?
./tools/api/commands/install_profile udid update.mobileconfig
./tools/api/commands/profile_list udid

### What did you expect to see?
Expects the updated profile in device
 
### What did you see instead?
transport=http method=POST status=201 proto=HTTP/1.1 host=44.225.168.75 user_agent=curl/7.29.0 path=/v1/commands
level=info msg="queued event for device" device_udid=fxxxxxxxxxxxxxxxxxxx1 command_uuid=e0b681ac-13f7-4d49-95f5-49afee9b6e1a request_type=InstallProfile
the Topic header of the request was not specified and was required

transport=http method=POST status=201 proto=HTTP/1.1 host=44.225.168.75 user_agent=curl/7.29.0 path=/v1/commands
level=info msg="queued event for device" device_udid= fxxxxxxxxxxxxxxxxxxx1 command_uuid=648a0e70-5359-419b-a5dc-ac444c1f3004 request_type=ProfileList
the Topic header of the request was not specified and was required

**Comment by jessepeterson** [comment]
This seems like an APNs certificate (i.e. a configuration) issue — it appears Apple is rejecting the Push request because the topic and/or certificate is misconfigured. I'd take a look at configuring APNs here: https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate

Have you manually modified the enrollment profile at all? The topic needs to match the APNs certificate (as just one example of things you need to track if you do this manually.

Because this _seems_ to be a configuration issue I'm going to close this. (come join us on Slack if you'd like support in configuring MicroMDM). But if you suspect this is a bug in MicroMDM feel free to re-open the issue. Thanks!

**Comment by NithinMD** [comment]
Hi,

Like you said I modified the custom created enrollment profile with correct topic from APNS certificate. Then I tried install application command, but still getting the same output. 

transport=http method=POST status=201 proto=HTTP/1.1 host=44.225.168.75 user_agent=curl/7.29.0 path=/v1/commands
level=info msg="queued event for device" device_udid=fxxxxxxxxxxxxxxxxxxx1 command_uuid=8f2f6386-4f70-4e2f-94c3-a67aebceb7c7 request_type=InstallApplication

But this time **the topic header of the request was not specified and was required** message is not showing in logs.

I'm not able see any call made to APNS servers from MDM in logs. How can I ensure that the APNS calls are being made from MDM?

**Comment by jessepeterson** [comment]
> I'm not able see any call made to APNS servers from MDM in logs. How can I ensure that the APNS calls are being made from MDM?

I don't think we log successful APNs pushes being sent. You should see an error if there's problem sending the APNs push.

That said - does the device fully enroll? Does it send two check-ins on enroll? Does `apsctl` [show anything useful?](https://mosen.github.io/profiledocs/troubleshooting/apns.html) for when pushes were last received? Does [MDM debugging](https://github.com/micromdm/micromdm/wiki/Troubleshooting-MDM) show anything useful? (Also [here](https://micromdm.io/blog/troubleshoot-dep/)).

Again for MDM troubleshooting I highly recommend joining the Slack channel. This issue tracker is largely for bug/feature reporting.
