### ISSUE TITLE
simulated iPhone not shown with *mdmctl get devices*

### ISSUE THREAD

**Issue by TempHauns** [micromdm/micromdm#818]
### What version of `micromdm` are you using?
v1.9.0
### What `micromdm` command did you run?
mdmctl get devices
### What did you expect to see?
2 entries: one representing the iMAC + one representing the iPhone 
### What did you see instead?
1 entry: the iMAC

On both devices, the profile was enrolled successfully, both marked as "Verified".
The difference being that the iPhone does not get listed when executing "mdmctl get devices".
Enrollment Status of the iMAC is "true".
The IPhone is virtualized via XCode on the same iMAC if that is relevant. I did successfully enroll the iPhone on another MDM Software just to make sure it's not an issue of the virtualisation.
The Webhook only outputs the enrolling response of the iMac as well.

**Comment by korylprince** [comment]
Can you post the MicroMDM logs (e.g. what `micromdm serve` writes to stdout) from when the iPhone enrolls?

I'm not sure a simulated iPhone can be properly enrolled in an MDM. My brief research did not find very much information, but what I could find suggested this would not work properly.

**Comment by korylprince** [comment]
For a proper enrollment, I would expect to see something like this following those last lines in your log:

```
transport=http method=PUT status=200 proto=HTTP/1.1 host=<ip> user_agent="MDM-OSX/1.0 mdmclient/1543" path=/mdm/checkin
level=debug msg="re-enrolling device" serial=<serial>
```

My guess is the simulated iPhone is not going to actually enroll since it doesn't have a hardware ID. As time allows, I'll see if I can't test it against my server.

**Comment by korylprince** [comment]
I've set up mitmproxy to capture requests from the simulated iPhone, and it does not attempt any requests beyond the SCEP exchange.

I was able to enroll a real iPhone (iOS 13 and iOS 15) without any issues.

It appears the simulated iPhone will request a SCEP cert, but not actually enroll itself. Again, I think this has to do with it not having a hardware ID. At this point I think it's safe to say it's not possible.

If you're able to find additional information about this that might suggest otherwise, feel free to reopen this issue.
