### ISSUE TITLE
The MDM payload "com.github.micromdm.micromdm.enroll.mdm" is missing the topic.

### ISSUE THREAD

**Issue by Goozoon** [micromdm/micromdm#830]
### What version of `micromdm` are you using?
1.9 and for testing purposes using https://mdmcert.download/ instead of Apple's MDM CSR

### What `micromdm` command did you run?
` mdmctl mdmcert upload -cert /home/alex/mdm-certificates/MDM_\ McMurtrie\ Consulting\ LLC_Certificate-20220622.pem -password=***** -private-key /home/alex/mdm-certificates/mdmcert.download.push.key`

### What did you expect to see?
Success

### What did you see instead?
First time i ran i got this

`upload push certificate and key to server: Put "https://mdm.mydomain.com/v1/config/certificate": dial tcp: lookup mdm.mydomain.com on 127.0.0.53:53: read udp 127.0.0.1:47683->127.0.0.53:53: i/o timeout`

then i run it again and got
`upload push certificate and key to server: Put "https://mdm.mydomain.com/v1/config/certificate": x509: certificate signed by unknown authority`

**Comment by jessepeterson** [comment]
Looks like you're having trouble with `mdmctl` connecting to your MicroMDM instance. In the former case I don't know what's going on — looks like a DNS timeout issue? In the latter case it seems like you might be using self-signed certificate or something. Check out this [wiki on self-signed certs](https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-self-signed-certificates) (specifically the `-skip-verify` switch to `mdmctl`.

Once you get your push certificate uploaded then the `Topic` in the URL should be populated. Since this seems like a configuration issue I'm going to close this issue. Feel free to re-open or comment if you think there's a bug with MicroMDM here. Otherwise join us in #micromdm channel on Slack to help troubleshoot.

**Comment by Goozoon** [comment]
Both binaries are running on the same ubuntu and cert im trying to use is the one downloaded from apple site
Will check dns resolve.. but cant do anything with cert. Made all as per steps from documentation

**Comment by korylprince** [comment]
There are multiple certs involved in the setup. The one from Apple is the Push cert. But MicroMDM needs its own cert for HTTPS, and that's the one you're having issues with in the second error you posted.

**Comment by Goozoon** [comment]
It is a wildcard certificate im using also elsewhere, exchange for example
