### ISSUE TITLE
Fail to use send push endpoint

### ISSUE THREAD

**Issue by dimaskhln** [micromdm/micromdm#913]
### What version of `micromdm` are you using?

v1.11.0

### What `micromdm` command did you run?

`POST v1/push/:udid`

### What did you expect to see?

expect to send a push notification to device to check it's connection to APNs

### What did you see instead?

`PushInfo by UDID: not found: PushInfo udid <device_udid>`

**Comment by jessepeterson** [comment]
Sounds like the device wasn't properly enrolled (and so MicroMDM is reporting that it can't find the enrolled metadata for the device). Can you provide logs? Does the device seem to enroll okay?

**Comment by dimaskhln** [comment]
@jessepeterson yes, the other endpoints like `v1/commands` or `v1/checkin` works well and mdm commands are completing perfectly.
Here is a piece of logs related to `push` command
```
2023-08-04 13:53:07 transport=http method=GET status=200 proto=HTTP/1.1 host=172.23.0.4 user_agent=axios/1.2.1 path=/v1/config/certificate
2023-08-04 13:53:07 level=info component=apns method=Push udid=31530d80-17a8-5200-8fea-abf054775167 err="retrieving PushInfo by UDID: not found: PushInfo udid 31530d80-17a8-5200-8fea-abf054775167" took=107.583µs
2023-08-04 13:53:07 transport=http method=POST status=500 proto=HTTP/1.1 host=172.23.0.4 user_agent=axios/1.2.1 path=/v1/push/31530d80-17a8-5200-8fea-abf054775167
```

**Comment by korylprince** [comment]
That's very strange. More so that commands are working correctly, which requires the UDID to queue the command, and sends a push notification to cause the device to check in.

Not to belabor the point, but are you absolutely sure you're sending the UDID correctly? e.g. can you:

- run `mdmctl get devices -serials <your serial>`
- copy and paste the UDID from that output
- use the [send_push_notification](https://github.com/micromdm/micromdm/blob/main/tools/api/send_push_notification) tool to send the push notification.

**Comment by dimaskhln** [comment]
Thanks to your recommendations, I just discovered that UDID for `/push` endpoint must be in uppercase 😐
It wasn't really obvious for me, or maybe I read the docs inattentively.
Anyway, thank you!
