### ISSUE TITLE
Is it possible to listen the "Leave Remote Management" event?

### ISSUE THREAD

**Issue by dstmath** [micromdm/micromdm#997]
### What version of `micromdm` are you using?
1.12.1
### What `micromdm` command did you run?
I tapped the button "Leave Remote Management" on my iphone.
### What did you expect to see?
micromdm received the event.
### What did you see instead?
micromdm shows nothing.

Is it possible to listen the "Leave Remote Management" event?

**Comment by groob** [comment]
CheckOut events are part of the workflow web hooks already. 
https://github.com/micromdm/micromdm/blob/d442653826b6a93e15339ada542666214d4cfcb5/workflow/webhook/webhook.go#L108C1-L109C51

The only caveat is that the server might not see a CheckOut event. There's no guarantee that the device will send it to the server, because it will un-enroll from MDM even if networking is not available.

**Comment by dstmath** [comment]
@groob I have set CheckOutWhenRemoved to true, and set the webhook url ,other event has received normal. And when I tap Leave Remote Management, the internet is OK, but Neither the micromdm or the webhook received the event.

**Comment by jessepeterson** [comment]
Likely not a MicroMDM issue. Do you see an HTTP log? If the decide isn't sending it, there's nothing MicroMDM can do about it. You're welcome to file feedback with Apple:

- https://developer.apple.com/bug-reporting/
-  https://developer.apple.com/news/?id=vvrgkboh
- https://blog.kandji.io/testing-prerelease-operating-systems-apple (at the bottom "providing feedback")
-

**Comment by dstmath** [comment]
http log shows micromdm does not receive the event。Thanks。
